### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by pablojordandlf** [adrianhajdin/portfolio_website#35]
Hey! When running the project in dev I get the following error:

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133790:18)
    at BulkUpdateDecorator.update (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133692:50)
    at OriginalSource.updateHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack-sources2\index.js:1:19148)
    at NormalModule._initBuildHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65772:17)
    at handleParseResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65837:10)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65928:4
    at processResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65651:11)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65711:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133790:18)
    at BulkUpdateDecorator.update (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133692:50)
    at OriginalSource.updateHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack-sources2\index.js:1:19148)
    at NormalModule._initBuildHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65772:17)
    at handleParseResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65837:10)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65928:4
    at processResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65651:11)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65711:5
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133790:18)
    at BulkUpdateDecorator.update (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:133692:50)
    at OriginalSource.updateHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack-sources2\index.js:1:19148)
    at NormalModule._initBuildHash (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65772:17)
    at handleParseResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65837:10)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65928:4
    at processResult (C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65651:11)
    at C:\Users\pablo\Documents\GitHub\portfolio_website\node_modules\next\dist\compiled\webpack\bundle5.js:65711:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by Andres22-sys** [comment]
I have the same issue, I've been trying to figure it out for about a day!!!

**Comment by zakjanzi** [comment]
I got this same issue when I first cloned the site and wanted to run it locally. Turns out this is a node version issue.
This helped me understand and solve this problem: https://itsmycode.com/error-digital-envelope-routines-unsupported/

(Although it might not be best practice, so take it with a grain of salt).

**Comment by kewlkarthik** [comment]
I have the same issue :(

**Comment by turtlelord-17** [comment]
same issue. cant move on with the project.

**Comment by AJ-KUSHWAH** [comment]
same issue is arising with me.

**Comment by kevinbism** [comment]
I resolved upgrading the nextjs version. Try it. It works for me.

**Comment by leanhvu21042001** [comment]
### I have fixed it.
Just change your node-version.
Change to **node version 16**, it should work well on that version

You can use NVM

**Comment by websam101** [comment]
For those who is still having this issue, you can just modify the `package.json` file.

Linux:
```json
  "scripts": {
    "dev": "export NODE_OPTIONS=--openssl-legacy-provider && next dev",
    "build": "export NODE_OPTIONS=--openssl-legacy-provider && next export",
    "start": "export NODE_OPTIONS=--openssl-legacy-provider && next start"
  },
```

Windows:
```json
  "scripts": {
    "dev": "set NODE_OPTIONS=--openssl-legacy-provider && next dev",
    "build": "set NODE_OPTIONS=--openssl-legacy-provider && next export",
    "start": "set NODE_OPTIONS=--openssl-legacy-provider && next start"
  },
```

or by adding [cross-env](https://www.npmjs.com/package/cross-env) `npm install cross-env`
```json
  "scripts": {
    "dev": "cross-env NODE_OPTIONS=--openssl-legacy-provider && next dev",
    "build": "cross-env NODE_OPTIONS=--openssl-legacy-provider && next export",
    "start": "cross-env NODE_OPTIONS=--openssl-legacy-provider && next start"
  },
```

**Comment by markogra** [comment]
@websam101 Thanks, works well for windows
